const game = (record) => Object.freeze(record);
const theme = (className, primary, accent, ink = "#ffffff") => Object.freeze({ className, primary, accent, ink });

// The only portfolio source of truth. Navigation, hero states, cards, routes, statuses,
// actions, imagery, and game-specific color all derive from these records.
export const gameCatalog = Object.freeze([
  game({ id: "palace", key: "palace", title: "Palace", shortTitle: "Palace", slug: "palace", shortDescription: "Outplay the table. Empty your hand. Take the Palace.", description: "Match or beat the pile, master four power cards, and survive the final hidden card.", artwork: "assets/icon-palace-4hearts.webp", heroArtwork: "assets/palace-hero-1024.webp", alt: "Palace castle artwork from Four of Hearts Interactive", imageFocalPoint: "50% 46%", status: "Interactive Preview", availability: "Playable website mini-match", genre: "Competitive card game", primaryAction: "palace-play.html", primaryActionLabel: "Play Palace", secondaryAction: "palace.html", secondaryActionLabel: "Explore Palace", infoUrl: "palace.html", playUrl: "palace-play.html", playLabel: "Play Palace", theme: theme("palace", "#075cc7", "#ffd34d", "#061b3c"), featured: true, featuredPriority: 1, sortOrder: 10, playable: true }),
  game({ id: "bobby", key: "bobby", title: "Bobby the Breadasaurus", shortTitle: "Bobby", slug: "bobby-the-breadasaurus", shortDescription: "Collect bread, explore colorful worlds, and bring Bobby's friends home.", description: "A warm platform adventure about a brave little dinosaur finding the way back to the herd.", artwork: "assets/bobby/bobby-character-720.webp", heroArtwork: "assets/bobby/bobby-hero-1200.webp", alt: "Bobby the Breadasaurus running through a colorful prehistoric bread world", imageFocalPoint: "58% 48%", status: "In Development", availability: "Concept development", genre: "Family platform adventure", primaryAction: "bobby-the-breadasaurus.html", primaryActionLabel: "Meet Bobby", secondaryAction: "news-bobby-the-breadasaurus-joins-the-family.html", secondaryActionLabel: "Development Note", infoUrl: "bobby-the-breadasaurus.html", playUrl: null, playLabel: null, theme: theme("bobby", "#cf5b20", "#ffd768", "#2b160a"), featured: true, featuredPriority: 2, sortOrder: 20, playable: false }),
  game({ id: "evil-doom", key: "evil-doom", title: "Evil Doom Adventures: Shadow Run", shortTitle: "Shadow Run", slug: "evil-doom-adventures-shadow-run", shortDescription: "Run the shadows, beat the traps, and rescue your partner.", description: "Two shadow heroes race through dangerous worlds on a rescue mission built around trust, timing, and motion.", artwork: "assets/evil-doom/evil-doom-heroes-purple-1200.webp", heroArtwork: "assets/evil-doom/evil-doom-hero-purple-1200.webp", alt: "Evil Doom Boy and Evil Doom Girl in a moonlit shadow world", imageFocalPoint: "58% 46%", status: "In Development", availability: "Concept development", genre: "Action platformer", primaryAction: "evil-doom-adventures.html", primaryActionLabel: "Enter Shadow Run", secondaryAction: "news-shadow-run-enters-development.html", secondaryActionLabel: "Development Note", infoUrl: "evil-doom-adventures.html", playUrl: null, playLabel: null, theme: theme("evil-doom", "#111217", "#4E2A84"), featured: true, featuredPriority: 3, sortOrder: 30, playable: false }),
  game({ id: "thumb-command", key: "thumb-command", title: "Thumb Command", shortTitle: "Thumb Command", slug: "thumb-command", shortDescription: "Save Planet Earth. Launch the Blueguard, defend the city, and stop the invasion.", description: "Command the Blueguard, defend the cities of Earth, and stop a vivid alien invasion in a fast space-defense arcade campaign.", artwork: "assets/thumb-command/thumb-command-app-icon-768.webp", heroArtwork: "assets/thumb-command/thumb-command-chicago-gameplay-1600.jpg", alt: "Blueguard interceptor defending Chicago from a purple alien fleet", imageFocalPoint: "50% 50%", status: "In Development", availability: "No public build or release date announced", genre: "Arcade defense", primaryAction: "thumb-command.html", primaryActionLabel: "See the Mission", secondaryAction: "news-thumb-command-save-planet-earth.html", secondaryActionLabel: "Latest Transmission", infoUrl: "thumb-command.html", playUrl: null, playLabel: null, theme: theme("thumb-command", "#061a35", "#ffc52f"), featured: true, featuredPriority: 4, sortOrder: 40, playable: false }),
  game({ id: "hearts", key: "hearts", title: "Hearts", shortTitle: "Hearts", slug: "hearts", shortDescription: "Dodge the points—or take every one.", description: "Read the table, manage the danger, and decide when to shoot the moon.", artwork: "assets/icon-hearts-4hearts.webp", heroArtwork: "assets/icon-hearts-4hearts.webp", alt: "Hearts ruby artwork from Four of Hearts Interactive", imageFocalPoint: "50% 50%", status: "Internal Alpha", availability: "Website lesson available", genre: "Trick-taking card game", primaryAction: "hearts-play.html", primaryActionLabel: "Preview Hearts", secondaryAction: null, secondaryActionLabel: null, infoUrl: "hearts-play.html", playUrl: null, playLabel: null, theme: theme("hearts", "#a8071c", "#ff616f"), featured: false, featuredPriority: 5, sortOrder: 50, playable: false }),
  game({ id: "spades", key: "spades", title: "Spades", shortTitle: "Spades", slug: "spades", shortDescription: "Bid together. Let trump speak.", description: "Call the contract, count the tricks, and work as a team.", artwork: "assets/icon-spades-4hearts.webp", heroArtwork: "assets/icon-spades-4hearts.webp", alt: "Spades royal-purple artwork from Four of Hearts Interactive", imageFocalPoint: "50% 50%", status: "Internal Alpha", availability: "Website lesson available", genre: "Partnership card game", primaryAction: "spades-play.html", primaryActionLabel: "Preview Spades", secondaryAction: null, secondaryActionLabel: null, infoUrl: "spades-play.html", playUrl: null, playLabel: null, theme: theme("spades", "#2f126d", "#a66cff"), featured: false, featuredPriority: 6, sortOrder: 60, playable: false }),
  game({ id: "euchre", key: "euchre", title: "Euchre", shortTitle: "Euchre", slug: "euchre", shortDescription: "Call trump. Find the bowers. Move fast.", description: "A quick partnership battle where the bowers can turn the whole hand.", artwork: "assets/icon-euchre-4hearts.webp", heroArtwork: "assets/icon-euchre-4hearts.webp", alt: "Euchre emerald artwork from Four of Hearts Interactive", imageFocalPoint: "50% 50%", status: "Internal Alpha", availability: "Website lesson available", genre: "Partnership card game", primaryAction: "euchre-play.html", primaryActionLabel: "Preview Euchre", secondaryAction: null, secondaryActionLabel: null, infoUrl: "euchre-play.html", playUrl: null, playLabel: null, theme: theme("euchre", "#145e32", "#72d86b"), featured: false, featuredPriority: 7, sortOrder: 70, playable: false })
]);

export const primaryGames = gameCatalog;
export const featuredGames = gameCatalog.filter(({ featured }) => featured).sort((a, b) => a.featuredPriority - b.featuredPriority);
export const gameByKey = Object.freeze(Object.fromEntries(gameCatalog.map((record) => [record.key, record])));