const heroPicture = (eager = false) => "<picture class='gildenspire-picture'><source media='(max-width:700px)' srcset='assets/gildenspire/gildenspire-hero-960.webp'><img src='assets/gildenspire/gildenspire-hero-1600.webp' alt='A red dragon and rider flying above the enormous fantasy world of GildenSpire while a rival dragon approaches' width='1600' height='900' " + (eager ? "fetchpriority='high'" : "loading='lazy'") + "></picture>";

export const gildenspireHomeFeature = () => "<section class='gildenspire-home-feature' aria-labelledby='gildenspire-home-title'><div class='production-shell gildenspire-feature-grid'><div class='gildenspire-feature-copy'><p class='production-eyebrow'>NEW FROM FOUR OF HEARTS INTERACTIVE</p><h2 id='gildenspire-home-title'>GildenSpire</h2><strong>FLIGHT OR FIGHT</strong><p>Raise a dragon. Explore an enormous world. Fight for the sky.</p><a class='button gildenspire-button' href='gildenspire.html'>Explore GildenSpire</a></div>" + heroPicture() + "</div></section>";

export const gildenspireGamesFeature = () => "<section class='gildenspire-games-feature' aria-labelledby='gildenspire-games-title'><div class='production-shell gildenspire-feature-grid'>" + heroPicture() + "<div class='gildenspire-feature-copy'><p class='production-eyebrow'>IN DEVELOPMENT</p><h2 id='gildenspire-games-title'>GildenSpire</h2><strong>FLIGHT OR FIGHT</strong><p>Raise your dragon. Take to the skies. Discover a world built to be flown through—and fought for.</p><a class='button gildenspire-button' href='gildenspire.html'>Discover GildenSpire</a></div></div></section>";

const species = [
  ["Emberclaw", "Firepower with weight behind it."],
  ["Frostveil", "Cold air. Clean lines. A different fight."],
  ["Verdantis", "Power drawn from the living world."],
  ["Tidalis", "Built for coastlines, storms, and open water."],
  ["Skysong", "Light, quick, and at home above the clouds."],
  ["Stormcrest", "Thunder made airborne."],
  ["Duneheart", "Endurance shaped by heat and distance."],
  ["Shadowmire", "Low light, quiet wings, patient power."],
  ["Obsidian", "Armoured, imposing, and hard to move."],
  ["Dawnplume", "A bright silhouette against the morning sky."],
  ["Moonlace", "Graceful flight with an unusual rhythm."],
  ["Aurum", "The legend beyond the Golden Egg."]
];

export const gildenspirePageContent = () => [
  "<article class='gildenspire-page'>",
  "<header class='gildenspire-hero'>", heroPicture(true), "<div class='gildenspire-hero-shade' aria-hidden='true'></div>",
  "<div class='production-shell gildenspire-hero-copy'><p class='production-eyebrow'>COMING FROM FOUR OF HEARTS INTERACTIVE</p><h1>GildenSpire</h1><strong>FLIGHT OR FIGHT</strong><p>Raise your dragon. Take to the skies. Discover an enormous fantasy world—and when something decides the sky belongs to them, prove otherwise.</p><div class='actions'><a class='button gildenspire-button' href='#raise'>Discover GildenSpire</a><a class='button secondary' href='news-introducing-gildenspire-flight-or-fight.html'>Read the Development News</a></div><span class='gildenspire-status'>In Development · No public release date announced</span></div></header>",
  "<nav class='gildenspire-subnav' aria-label='GildenSpire sections'><div class='production-shell'><strong>GildenSpire</strong><div><a href='#raise'>Raise</a><a href='#fly'>Fly</a><a href='#fight'>Fight</a><a href='#dragons'>Dragons</a><a href='#golden-egg'>Golden Egg</a><a href='#development'>Development</a></div></div></nav>",
  "<section class='gildenspire-flight-manifesto' aria-labelledby='gildenspire-manifesto-title'><div class='production-shell'><p class='production-eyebrow'>THE SKY IS ONLY THE BEGINNING</p><h2 id='gildenspire-manifesto-title'>Fly farther.<br>Fight harder.<br><em>Grow legendary.</em></h2><p>GildenSpire is being built around the thrill of direct flight: climbing, diving, banking, exploring, discovering—and fighting when the open sky stops being friendly.</p></div></section>",
  "<section class='gildenspire-core' aria-label='The GildenSpire game loop'><div class='production-shell gildenspire-core-grid'>",
  "<article id='raise'><img src='assets/gildenspire/gildenspire-raise-960.webp' alt='A young GildenSpire dragon training beside a fantasy castle' width='960' height='639' loading='lazy'><div><span>01 · RAISE</span><h2>Raise a Legend</h2><p>Every GildenSpire dragon begins small. Hatch it, feed it, train it, build a bond with it, and watch it develop into something much more powerful.</p><p>Different dragons are being designed with genuinely different shapes, powers, movement characteristics, strengths, and personalities.</p></div></article>",
  "<article id='fly'><img src='assets/gildenspire/gildenspire-fly-960.webp' alt='A rider flying a red dragon through islands, castles, mountains, and waterfalls' width='960' height='548' loading='lazy'><div><span>02 · FLY</span><h2>The World Is Bigger From Up Here</h2><p>Flying is not transportation between menus. Flying is part of the game.</p><p>Take direct control and cross cliffs, islands, castles, ruins, secrets, weather, and places that can only be reached from the sky.</p></div></article>",
  "<article id='fight'><img src='assets/gildenspire/gildenspire-fight-960.webp' alt='Red and blue dragons meeting in fast aerial combat' width='960' height='667' loading='lazy'><div><span>03 · FIGHT</span><h2>Own the Sky</h2><p>Exploration becomes flight-or-fight when something else claims the air.</p><p class='gildenspire-combat-line'>Dive. Climb. Bank. Dodge. Chase. Attack.</p><p>Different dragons will bring different abilities to kinetic aerial battles, with team play planned for larger threats.</p></div></article>",
  "</div></section>",
  "<section class='gildenspire-dragons' id='dragons' aria-labelledby='dragons-title'><div class='production-shell'><div class='gildenspire-section-heading'><p class='production-eyebrow'>DIFFERENT DRAGONS. DIFFERENT POWERS.</p><h2 id='dragons-title'>Dragons of GildenSpire</h2><p>The world of GildenSpire is being built around dragons that are more than color swaps. Different silhouettes. Different movement. Different powers. Different ways to fly and fight.</p><p class='gildenspire-development-note'>These species define the current creative direction; development and implementation will continue to evolve.</p></div><div class='gildenspire-dragons-layout'><img src='assets/gildenspire/gildenspire-dragons-960.webp' alt='A collection of substantially different GildenSpire dragon species' width='960' height='830' loading='lazy'><ul>",
  species.map((item) => "<li><strong>" + item[0] + "</strong><span>" + item[1] + "</span></li>").join(""),
  "</ul></div></div></section>",
  "<section class='gildenspire-golden' id='golden-egg' aria-labelledby='golden-title'><div class='production-shell gildenspire-golden-grid'><img src='assets/gildenspire/gildenspire-golden-960.webp' alt='The legendary Golden Egg displayed in an ancient GildenSpire sanctuary' width='960' height='727' loading='lazy'><div><p class='production-eyebrow'>THE ULTIMATE GOAL</p><h2 id='golden-title'>THE GOLDEN EGG</h2><p>Some dragons are found.</p><p>Some are raised.</p><p>Some have to be earned.</p><p class='gildenspire-golden-reveal'>At the far end of GildenSpire's progression lies the Golden Egg—and the legendary dragon waiting inside it.</p></div></div></section>",
  "<section class='gildenspire-development' id='development' aria-labelledby='development-title'><div class='production-shell'><header><p class='production-eyebrow'>FROM THE 4OH WORKBENCH</p><h2 id='development-title'>Building the sky.</h2><p>Three development notes about the standards behind GildenSpire.</p></header><div class='gildenspire-news-grid'><a href='news-introducing-gildenspire-flight-or-fight.html'><span>DEVELOPMENT</span><strong>Introducing GildenSpire: Flight or Fight</strong><em>Read the dispatch ↗</em></a><a href='news-why-flying-has-to-be-fun.html'><span>DESIGN</span><strong>Why Flying Has to Be Fun</strong><em>Read the dispatch ↗</em></a><a href='news-building-dragons-that-actually-feel-different.html'><span>CREATURES</span><strong>Building Dragons That Actually Feel Different</strong><em>Read the dispatch ↗</em></a></div><p class='gildenspire-status-card'><strong>Current status: In Development</strong><span>GildenSpire is not publicly downloadable. No store release or launch date has been announced.</span></p></div></section>",
  "</article>"
].join("");
