const text=(en,ca)=>`<span data-copy-en="${en.replaceAll('"','&quot;')}" data-copy-ca="${ca.replaceAll('"','&quot;')}">${en}</span>`;
const canadianStatus={"Interactive Preview":"Interactive preview. Pull up a chair.","Internal Alpha":"Internal alpha. Still wearing work boots.","In Development":"In development. We measured twice."};
const canadianCta={palace:"Play Palace, bud",hearts:"Meet Hearts",spades:"Meet Spades",euchre:"Meet Euchre",solitaire:"Meet Solitaire",war:"Meet War","thumb-command":"Save Earth, bud",bobby:"Meet Bobby and the herd","evil-doom":"Choose your hero, carefully",heartstack:"See HeartStack","princess-land":"Explore Princess Land","unicorn-land":"Explore Unicorn Land","people-lens":"See People Lens","sleep-amigo":"Meet Sleep Amigo"};
const status=(product)=>`<span class="production-status"><span aria-hidden="true">●</span> ${text(product.status,canadianStatus[product.status]||product.status)}</span>`;
const picture=(product,eager=false)=>`<img src="${product.artwork}" alt="${product.alt}" width="1024" height="1024" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;

const canadianSummary={
 "thumb-command":"Aliens are dropping in uninvited. Very rude. Save Earth, bud.",
 bobby:"Build the towers, hold the path, and protect the Breadstone. No pressure, eh.",
 "evil-doom":"Pick a hero, run like somebody forgot the Zamboni, and bring the other one home.",
 heartstack:"Match the suits, make a ridiculous combo, and free the unicorns. Beauty.",
 "princess-land":"Style a heroine, shape a castle, and make every room nicer than a lake cabin.",
 "unicorn-land":"Create a unicorn, grow a habitat, and keep the sparkle situation under control.",
 palace:"House rules, burns, resets, and at least one person insisting their family plays it correctly.",
 hearts:"Take the tricks, dodge the points, and remain politely competitive.",
 spades:"Bid boldly. Bag carefully. Apologize afterward.",
 euchre:"Five cards, one trump suit, and a suspicious amount of confidence.",
 solitaire:"Just you, the deck, and one more deal before bed.",
 war:"Flip the cards. Highest wins. Diplomacy was attempted.",
 "people-lens":"Keep useful people context organized instead of letting it pile up like driveway snow.",
 "sleep-amigo":"Sleep questions, daily insights, and a history that remembers more than you do before coffee."
};

export const productTile=(product,{eager=false,compact=false}={})=>`<a class="production-tile ${compact?'compact':''}" href="${product.infoUrl}" aria-label="${product.title}: ${product.type}" style="--tile-accent:${product.theme.accent}">
  <span class="production-tile-art">${picture(product,eager)}</span>
  <span class="production-tile-copy"><strong>${product.shortTitle}</strong><small>${product.type}</small>${status(product)}</span>
</a>`;

export const productCard=(product)=>`<a class="production-card" href="${product.infoUrl}" style="--card-accent:${product.theme.accent}">
  <span class="production-card-art">${picture(product)}</span>
  <span class="production-card-copy"><span class="production-kicker">${product.genre}</span><strong>${product.title}</strong><span>${text(product.summary,canadianSummary[product.key]||product.summary)}</span><em>${text(`${product.cta} ↗`,`${canadianCta[product.key]||product.cta} ↗`)}</em></span>
</a>`;

const productPanel=(games)=>`<div class="production-product-panel" aria-label="Games from Four of Hearts Interactive">${games.map((p,i)=>productTile(p,{eager:i<2,compact:true})).join("")}<a class="production-app-link" href="lifestyle-apps.html">${text("Looking for useful apps? Meet People Lens and Sleep Amigo. ↗","Looking for useful apps? People Lens and Sleep Amigo are over here, bud. ↗")}</a></div>`;

export const nameStory=()=>`<section class="production-name-story" aria-labelledby="name-story-title"><div class="name-motif" aria-hidden="true">4OH</div><div class="production-shell production-name-grid"><div><p class="production-eyebrow">${text("THE NAME","THE NAME, EH")}</p><h2 id="name-story-title">${text("4. Ohhh. Now you get it.","4. Ohhh. Beauty.")}</h2></div><div><h3>${text("Four of Hearts became 4OH. Then somebody said it out loud.","Four of Hearts became 4OH. We said it out loud, apologized to the alphabet, and carried on.")}</h3><p>${text("We started with card games and a fourth heart. The name stuck. So did the instinct to make software with personality. Today we build original games and useful apps—independently, carefully, and with just enough mischief to keep it interesting.","We started with card games and one extra heart. Now we make original games and useful apps with prairie grit, decent manners, and enough coffee to prevent an international incident.")}</p><a href="about.html#the-name">${text("The unnecessarily complete explanation ↗","The full yarn, bud ↗")}</a></div></div></section>`;

const collection=(id,eyebrow,title,products)=>`<section class="production-collection" id="${id}"><div class="production-shell"><header><p class="production-eyebrow">${eyebrow}</p><h2>${title}</h2></header><div class="production-card-grid">${products.map(productCard).join("")}</div></div></section>`;

export const homepage=({groups,apps,news,articleFile,formatDate})=>`<section class="production-hero production-home-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">${text("INDEPENDENT SOFTWARE · BUILT IN SOUTH DAKOTA","INDEPENDENT SOFTWARE · BUILT ON THE PRAIRIE, EH")}</p><h1>${text("Independent software.","Independent software.")}<em>${text("Built with a point of view.","No committee. Sorry, committee.")}</em></h1><p>${text("Original games, useful apps, and a few ideas that got out of hand—in the best possible way.","Original games, useful apps, prairie grit, decent manners, and a double-double kept within responsible reach.")}</p><div class="actions"><a class="button" href="games.html">Explore games</a><a class="button secondary" href="lifestyle-apps.html">Lifestyle apps</a></div></div>${productPanel([...groups["arcade-adventure"],...groups["puzzle-creative"],...groups["card-games"]])}</div></section>
${nameStory()}
<section class="production-lineup-intro"><div class="production-shell"><p class="production-eyebrow">THE CURRENT 4OH LINEUP</p><h2>What we’re making.</h2><p>Original games, familiar card tables, creative worlds, and a growing collection of useful apps.</p></div></section>
${collection("arcade-adventure","ARCADE, DEFENSE & ADVENTURE","Fast reflexes. Big worlds.",groups["arcade-adventure"])}
${collection("puzzle-creative","PUZZLE & CREATIVE WORLDS","Make a match. Make a world.",groups["puzzle-creative"])}
${collection("card-table","THE CARD TABLE","One more hand.",groups["card-games"])}
<section class="production-app-bridge"><div class="production-shell"><p class="production-eyebrow">LIFESTYLE APPS</p><h2>Useful software.<br><em>Same independent streak.</em></h2><div class="production-app-grid">${apps.map(productCard).join("")}</div><a class="button" href="lifestyle-apps.html">Explore lifestyle apps</a></div></section>
<section class="production-news"><div class="production-shell"><header><p class="production-eyebrow">LATEST FROM 4OH</p><h2>Notes from the workbench.</h2></header><div class="production-news-grid">${news.slice(0,3).map(item=>`<a href="${articleFile(item.slug)}"><time datetime="${item.date}">${formatDate(item.date)}</time><strong>${item.title}</strong><span>${item.description}</span><em>Read dispatch ↗</em></a>`).join("")}</div></div></section>`;

export const gamesPage=({groups})=>`<section class="production-hero production-games-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">${text("INDEPENDENT SOFTWARE · BUILT IN SOUTH DAKOTA","GAMES FROM THE PRAIRIE")}</p><h1>${text("Games with a point of view.","Games with a point of view.")}<em>${text("Built independently.","Built independently, bud.")}</em></h1><p>${text("Card-table classics, arcade battles, strange little worlds, and ideas too good to leave in a notebook.","Card tables, arcade battles, strange little worlds, and absolutely no need to drop the gloves.")}</p></div>${productPanel([...groups["arcade-adventure"],...groups["puzzle-creative"],...groups["card-games"]])}</div></section>
<section class="production-lineup-intro"><div class="production-shell"><p class="production-eyebrow">THE CURRENT 4OH LINEUP</p><h2>What we’re making.</h2><p>Original games, familiar card tables, creative worlds, and a growing collection of useful apps.</p></div></section>
${collection("arcade-adventure","ARCADE, DEFENSE & ADVENTURE","Fast reflexes. Big worlds.",groups["arcade-adventure"])}
${collection("puzzle-creative","PUZZLE & CREATIVE WORLDS","Make a match. Make a world.",groups["puzzle-creative"])}
${collection("card-table","THE CARD TABLE","One more hand.",groups["card-games"])}`;

export const lifestylePage=({apps})=>`<section class="production-hero production-lifestyle-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">LIFESTYLE APPS FROM 4OH</p><h1>Useful software.<em>Same independent streak.</em></h1><p>Practical ideas, thoughtful tools, and technology designed to help without getting in the way.</p></div><div class="lifestyle-symbols" aria-hidden="true"><span>◎</span><span>☾</span></div></div></section><section class="production-apps-page"><div class="production-shell"><header><p class="production-eyebrow">BEYOND THE GAME TABLE</p><h2>Tools for the rest of the day.</h2><p>4OH also builds practical applications for understanding information, noticing useful patterns, and making everyday technology feel a little more human.</p></header><div class="production-app-grid">${apps.map(productCard).join("")}</div><div class="privacy-forward-note"><strong>Privacy-forward by design.</strong><p>These applications are in development. Their public pages make no claim of platform access, medical diagnosis, hidden data collection, or release availability.</p></div><a class="text-link" href="games.html">Back to Games ↗</a></div></section>`;

export const productPage=({product,related,newsHref})=>`<article class="production-detail" style="--product-accent:${product.theme.accent};--product-primary:${product.theme.primary}"><header class="production-detail-hero"><div class="production-shell production-detail-grid"><div><p class="production-eyebrow">${product.genre}</p><h1>${product.title}</h1><p class="production-detail-summary">${text(product.summary,canadianSummary[product.key]||product.summary)}</p><div class="production-detail-status">${status(product)}<span>${product.availability}</span></div><div class="actions">${product.playUrl?`<a class="button" href="${product.playUrl}">${product.playLabel}</a>`:''}<a class="button secondary" href="${product.category==='game'?'games.html':'lifestyle-apps.html'}">Back to ${product.category==='game'?'Games':'Lifestyle Apps'}</a></div></div><figure><img src="${product.heroArtwork}" alt="${product.alt}" width="1200" height="900" fetchpriority="high"><figcaption>Current product artwork · visual direction may evolve during development</figcaption></figure></div></header><section class="production-detail-body"><div class="production-shell production-detail-columns"><div><p class="production-eyebrow">THE CORE IDEA</p><h2>Clear enough to begin.<br>Interesting enough to continue.</h2><p>${product.description}</p><h3>What we are building</h3><ul><li>A focused product loop with readable choices and responsive feedback.</li><li>An accessible, family-friendly presentation with no dark-pattern design.</li><li>A development process that labels concepts honestly and avoids invented release promises.</li></ul>${product.category==='lifestyle'?'<div class="privacy-forward-note"><strong>Privacy note</strong><p>This concept is not a medical service and does not claim access to private platform data. Any future collection or processing must be disclosed before release.</p></div>':''}</div><aside><p class="production-eyebrow">CURRENT STATUS</p><h2>${product.status}</h2><p>${product.availability}.</p>${newsHref?`<a class="text-link" href="${newsHref}">Read the related studio dispatch ↗</a>`:''}</aside></div></section><section class="production-related"><div class="production-shell"><p class="production-eyebrow">RELATED PRODUCTS</p><h2>Keep exploring.</h2><div class="production-card-grid">${related.map(productCard).join("")}</div></div></section></article>`;
