import { privacyCopy } from "./privacy-copy.mjs";
import { gildenspireGamesFeature, gildenspireHomeFeature } from "./gildenspire-content.mjs";
const text=(en,ca)=>`<span data-copy-en="${en.replaceAll('"','&quot;')}" data-copy-ca="${ca.replaceAll('"','&quot;')}">${en}</span>`;
const canadianStatus={"Interactive Preview":"Interactive preview. Pull up a chair.","Internal Alpha":"Internal alpha. Still wearing work boots.","In Development":"In development. We measured twice."};
const canadianCta={gildenspire:"Discover GildenSpire",palace:"Play Palace, bud",hearts:"Meet Hearts",spades:"Meet Spades",euchre:"Meet Euchre",solitaire:"Meet Solitaire",war:"Meet War","thumb-command":"Save Earth, bud",bobby:"See Bobby’s defences","evil-doom":"Meet both heroes",heartstack:"See HeartStack","princess-land":"Visit Princess Land","unicorn-land":"Meet the unicorns","people-lens":"See People Lens","sleep-amigo":"Meet Sleep Amigo"};
const status=(product)=>`<span class="production-status"><span aria-hidden="true">●</span> ${text(product.status,canadianStatus[product.status]||product.status)}</span>`;
const picture=(product,eager=false)=>`<img src="${product.artwork}" alt="${product.alt}" width="1024" height="1024" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;

const canadianSummary={
 gildenspire:"Raise your dragon, take to the skies, and politely inform anything hostile that the sky is already occupied.",
 "thumb-command":"Aliens are dropping in uninvited. Very rude. Save Earth, bud.",
 bobby:"A bread dinosaur, a herd to protect, and a suspicious number of defensive towers. Beauty.",
 "evil-doom":"Evil Doom is closing in, which is awfully rude. Start as Evil Doom Boy or switch to Evil Doom Girl and send it packing, bud.",
 heartstack:"Match the suits, make a ridiculous combo, and free the unicorns. Beauty.",
 "princess-land":"Style the princesses, decorate the castle, make lunch, then rearrange everything.",
 "unicorn-land":"Meet the unicorn, fix the mane, shape the habitat, and add a sensible excess of flowers.",
 palace:"House rules, burns, resets, and at least one person insisting their family plays it correctly.",
 hearts:"Take the tricks, dodge the points, and remain politely competitive.",
 spades:"Bid boldly. Bag carefully. Apologize afterward.",
 euchre:"Five cards, one trump suit, and a suspicious amount of confidence.",
 solitaire:"Just you, the deck, and one more deal before bed.",
 war:"Flip the cards. Highest wins. Diplomacy was attempted.",
 "people-lens":"Describe who you’re looking for and narrow the public evidence before it piles up like driveway snow.",
 "sleep-amigo":"Sleep questions, daily insights, and a history that remembers more than you do before coffee."
};

export const productTile=(product,{eager=false,compact=false}={})=>`<a class="production-tile ${compact?'compact':''}" href="${product.infoUrl}" aria-label="${product.title}: ${product.type}" style="--tile-accent:${product.theme.accent}">
  <span class="production-tile-art">${picture(product,eager)}${product.key==="evil-doom"?`<span class="production-art-badge">Choose Your Hero</span>`:""}</span>
  <span class="production-tile-copy"><strong>${product.shortTitle}</strong><small>${product.type}</small>${status(product)}</span>
</a>`;

export const productCard=(product)=>`<a class="production-card" href="${product.infoUrl}" style="--card-accent:${product.theme.accent}">
  <span class="production-card-art">${picture(product)}${product.key==="evil-doom"?`<span class="production-art-badge">Choose Your Hero</span>`:""}</span>
  <span class="production-card-copy"><span class="production-kicker">${product.genre}</span><strong>${product.title}</strong><span>${text(product.summary,canadianSummary[product.key]||product.summary)}</span><em>${text(`${product.cta} ↗`,`${canadianCta[product.key]||product.cta} ↗`)}</em></span>
</a>`;

const productPanel=(games)=>`<div class="production-product-panel" aria-label="Games from Four of Hearts Interactive">${games.map((p,i)=>productTile(p,{eager:i<2,compact:true})).join("")}<a class="production-app-link" href="lifestyle-apps.html">${text("Looking for useful apps? Meet People Lens and Sleep Amigo. ↗","Looking for useful apps? People Lens and Sleep Amigo are over here, bud. ↗")}</a></div>`;

export const nameStory=()=>`<section class="production-name-story" aria-labelledby="name-story-title"><div class="name-motif" aria-hidden="true">4OH</div><div class="production-shell production-name-grid"><div><p class="production-eyebrow">${text("THE NAME","THE NAME, EH")}</p><h2 id="name-story-title">${text("4. Ohhh. I get it.","4. Ohhh. Beauty.")}</h2></div><div><h3>${text("Four of Hearts. Somebody said it out loud. The name stuck.","Four of Hearts. Somebody said it out loud. We gave a polite little nod and kept the name.")}</h3><p>${text("That is the whole story: Four of Hearts became 4OH. We began at the card table and kept building—original games, strange little worlds, and useful apps made independently in South Dakota.","No secret acronym, bud. Just Four of Hearts shortened into a tiny prairie revelation. We started at the card table and kept going—original games, strange little worlds, and useful apps made with care and a responsible amount of coffee.")}</p><p class="production-name-aside">${text("No secret acronym. No corporate mythology. Just Four of Hearts said out loud.","No corporate mythology. Just the full yarn, told politely.")}</p><a href="about.html#the-name">${text("The unnecessarily complete explanation ↗","The full yarn ↗")}</a></div></div></section>`;
export const privacySection=()=>`<section class="production-privacy" aria-labelledby="privacy-promise-title"><div class="production-shell production-privacy-grid"><div><p class="production-eyebrow">PRIVACY IS PART OF THE PRODUCT</p><h2 id="privacy-promise-title">${text(privacyCopy.headline,privacyCopy.headlineCanadian)}</h2><p>${text(privacyCopy.shortStatement,privacyCopy.shortStatementCanadian)}</p><p class="production-privacy-aside">${text("We do not need to know what kind of toilet paper you buy. We are sure it is fine.","We do not need to know what kind of toilet paper you buy. We trust your judgment, bud.")}</p><a class="text-link" href="privacy.html">${privacyCopy.learnMore}</a></div><ul class="production-trust-list"><li><span aria-hidden="true">↛</span>${privacyCopy.noAds}</li><li><span aria-hidden="true">◇</span>${privacyCopy.noSale}</li><li><span aria-hidden="true">⌂</span>${privacyCopy.localFirst}</li></ul></div></section>`;
const collection=(id,eyebrow,title,products)=>`<section class="production-collection" id="${id}"><div class="production-shell"><header><p class="production-eyebrow">${eyebrow}</p><h2>${title}</h2></header><div class="production-card-grid">${products.map(productCard).join("")}</div></div></section>`;

export const homepage=({groups,apps,news,articleFile,formatDate})=>`<section class="production-hero production-home-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">${text("FOUR OF HEARTS INTERACTIVE","FOUR OF HEARTS INTERACTIVE · HELLO FROM THE PRAIRIE")}</p><h1>${text("Games with heart.","Games with heart.")}<em>${text("Apps with purpose.","Apps with purpose. Beauty.")}</em></h1><p>${text("Fun, useful, privacy-minded software from an independent South Dakota studio that loves the craft.","Fun, useful, privacy-minded software from an independent South Dakota studio. Practically next door, by Canadian standards.")}</p><div class="actions"><a class="button" href="games.html">Explore games</a><a class="button secondary" href="lifestyle-apps.html">Explore apps</a></div></div>${productPanel([...groups["arcade-adventure"],...groups["puzzle-creative"],...groups["card-games"]])}</div></section>
${gildenspireHomeFeature()}
${nameStory()}
<section class="production-craft"><div class="production-shell production-craft-grid"><div><p class="production-eyebrow">THE CRAFT</p><h2>Old-school values.<br><em>Modern ambitions.</em></h2></div><div><p>Careful engineering. Thoughtful design. Testing on physical devices. Accessible defaults. Privacy considered before the first line ships.</p><p>Independent companies should still be allowed to make wonderfully strange things.</p></div></div></section>
${privacySection()}
<section class="production-lineup-intro"><div class="production-shell"><p class="production-eyebrow">THE CURRENT 4OH LINEUP</p><h2>Fun games. Great apps.</h2><p>One studio. Two useful instincts: make play worth your time, and make tools that earn their place on your device.</p></div></section>
${collection("arcade-adventure","ORIGINAL GAMES","Fun is serious work around here.",groups["arcade-adventure"])}
${collection("puzzle-creative","PUZZLE & CREATIVE PLAY","Strategy, silliness, and a lot of heart.",groups["puzzle-creative"])}
${collection("card-table","CLASSIC CARD GAMES","Deal us in.",groups["card-games"])}
<section class="production-app-bridge"><div class="production-shell"><p class="production-eyebrow">APPS WITH PURPOSE</p><h2>Useful software.<br><em>Less nonsense.</em></h2><p>We like software that actually does something: thoughtful tools, clear decisions, and privacy built into the plan.</p><div class="production-app-grid">${apps.map(productCard).join("")}</div><a class="button" href="lifestyle-apps.html">Explore apps</a></div></section>
<section class="production-news"><div class="production-shell"><header><p class="production-eyebrow">LATEST FROM 4OH</p><h2>Notes from the workbench.</h2></header><div class="production-news-grid">${news.slice(0,3).map(item=>`<a href="${articleFile(item.slug)}"><time datetime="${item.date}">${formatDate(item.date)}</time><strong>${item.title}</strong><span>${item.description}</span><em>Read dispatch ↗</em></a>`).join("")}</div></div></section>`;
export const gamesPage=({groups})=>`<section class="production-hero production-games-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">${text("GAMES WITH HEART · BUILT IN SOUTH DAKOTA","GAMES WITH HEART · BUILT ON THE PRAIRIE")}</p><h1>${text("Fun is serious work.","Fun is serious work.")}<em>${text("We brought snacks.","We brought snacks. And a toque.")}</em></h1><p>${text("Arcade battles, tactical bread dinosaurs, creative play, and card-table arguments worth having.","Arcade battles, tactical bread dinosaurs, creative play, and card-table arguments settled with excellent manners.")}</p></div>${productPanel([...groups["arcade-adventure"],...groups["puzzle-creative"],...groups["card-games"]])}</div></section>
${gildenspireGamesFeature()}
<section class="production-lineup-intro"><div class="production-shell"><p class="production-eyebrow">THE CURRENT 4OH LINEUP</p><h2>Games with a point of view.</h2><p>A little strategy. A little silliness. A lot of heart.</p></div></section>
${collection("arcade-adventure","ARCADE, DEFENSE & ADVENTURE","Fast reflexes. Specific trouble.",groups["arcade-adventure"])}
${collection("puzzle-creative","PUZZLE & CREATIVE PLAY","Make something worth keeping.",groups["puzzle-creative"])}
${collection("card-table","CLASSIC CARD GAMES","Deal us in.",groups["card-games"])}`;
export const lifestylePage=({apps})=>`<section class="production-hero production-lifestyle-hero"><div class="production-shell production-hero-grid"><div class="production-hero-copy"><p class="production-eyebrow">APPS WITH PURPOSE · BUILT BY 4OH</p><h1>Useful software.<em>Less nonsense.</em></h1><p>Thoughtful tools for real jobs, made by an independent studio that would rather solve the problem than decorate it with jargon.</p></div><div class="lifestyle-symbols" aria-hidden="true"><span>◎</span><span>☾</span></div></div></section><section class="production-apps-page"><div class="production-shell"><header><p class="production-eyebrow">FOR THE REST OF THE DAY</p><h2>Software should earn its place.</h2><p>People Lens and Sleep Amigo begin with a useful question, a clear job, and the belief that personal information should remain personal.</p></header><div class="production-app-grid">${apps.map(productCard).join("")}</div><div class="privacy-forward-note"><strong>Privacy considered from the start.</strong><p>These applications are in development. Their public pages make no claim of platform access, medical diagnosis, hidden data collection, or release availability.</p></div><a class="text-link" href="games.html">Back to Games ↗</a></div></section>`;
export const productPage=({product,related,newsHref})=>`<article class="production-detail" style="--product-accent:${product.theme.accent};--product-primary:${product.theme.primary}"><header class="production-detail-hero"><div class="production-shell production-detail-grid"><div><p class="production-eyebrow">${product.genre}</p><h1>${product.title}</h1><p class="production-detail-summary">${text(product.summary,canadianSummary[product.key]||product.summary)}</p><div class="production-detail-status">${status(product)}<span>${product.availability}</span></div><div class="actions">${product.playUrl?`<a class="button" href="${product.playUrl}">${product.playLabel}</a>`:''}<a class="button secondary" href="${product.category==='game'?'games.html':'lifestyle-apps.html'}">Back to ${product.category==='game'?'Games':'Lifestyle Apps'}</a></div></div><figure><img src="${product.heroArtwork}" alt="${product.alt}" width="1200" height="900" fetchpriority="high"><figcaption>Current product artwork · visual direction may evolve during development</figcaption></figure></div></header><section class="production-detail-body"><div class="production-shell production-detail-columns"><div><p class="production-eyebrow">THE CORE IDEA</p><h2>Clear enough to begin.<br>Interesting enough to continue.</h2><p>${product.description}</p><h3>What we are building</h3><ul><li>A focused product loop with readable choices and responsive feedback.</li><li>An accessible, family-friendly presentation with no dark-pattern design.</li><li>A development process that labels concepts honestly and avoids invented release promises.</li></ul><div class="privacy-forward-note"><strong>Product privacy status: ${product.privacyProfile.status}</strong><p>${product.privacyProfile.notes}</p></div></div><aside><p class="production-eyebrow">CURRENT STATUS</p><h2>${product.status}</h2><p>${product.availability}.</p>${newsHref?`<a class="text-link" href="${newsHref}">Read the related studio dispatch ↗</a>`:''}</aside></div></section><section class="production-related"><div class="production-shell"><p class="production-eyebrow">RELATED PRODUCTS</p><h2>Also on the workbench.</h2><div class="production-card-grid">${related.map(productCard).join("")}</div></div></section></article>`;
